export const galleryItems = [
  {
    title: "Bramley Row, Salford",
    caption: "Eight townhouses completed and handed over in a single phase.",
    image: "/images/properties/new-build-townhouses.jpeg",
    collection: "Property",
    tags: ["new build", "salford", "townhouse"],
    sort_order: 1,
  },
  {
    title: "Ordsall Quay",
    caption: "Corner plots on the quays, built for light.",
    image: "/images/properties/salford-townhouses.jpeg",
    collection: "Property",
    tags: ["salford", "townhouse"],
    sort_order: 2,
  },
  {
    title: "Crompton Place, Bolton",
    caption: "Town centre living above the retail core.",
    image: "/images/properties/town-centre-regeneration.jpeg",
    collection: "Regeneration",
    tags: ["bolton", "apartments", "regeneration"],
    sort_order: 3,
  },
  {
    title: "Heaton, Bolton",
    caption: "Established estates on the western edge of the town.",
    image: "/images/properties/suburban-estate.jpeg",
    collection: "Property",
    tags: ["bolton", "detached", "family"],
    sort_order: 4,
  },
  {
    title: "Churchgate",
    caption: "Bolton's oldest thoroughfare, still its busiest.",
    image: "/images/properties/bolton-high-street.jpeg",
    collection: "Regeneration",
    tags: ["bolton", "commercial", "high street"],
    sort_order: 5,
  },
  {
    title: "Bolton from above",
    caption: "A town centre in the middle of a £1bn masterplan.",
    image: "/images/properties/bolton-aerial.jpeg",
    collection: "Regeneration",
    tags: ["bolton", "aerial", "masterplan"],
    sort_order: 6,
  },
  {
    title: "Halliwell",
    caption: "Terraced streets that have underpinned yields for a decade.",
    image: "/images/properties/terraced-streets.jpeg",
    collection: "Property",
    tags: ["bolton", "investment", "terraces"],
    sort_order: 7,
  },
  {
    title: "Still Waters, Dusk",
    caption: "Reclaimed oak float frame, in situ.",
    image: "/images/art/still-waters-rustic.jpeg",
    collection: "Art",
    tags: ["landscape", "original", "living room"],
    sort_order: 8,
  },
  {
    title: "Still Waters — Gallery Edition",
    caption: "Hardwood and gilt, hung for a long sightline.",
    image: "/images/art/still-waters-classic.jpeg",
    collection: "Interiors",
    tags: ["limited edition", "hallway", "framing"],
    sort_order: 9,
  },
  {
    title: "Wee Rascal",
    caption: "Thousands of torn fragments, one terrier.",
    image: "/images/art/terrier-collage.jpeg",
    collection: "Art",
    tags: ["collage", "animal", "original"],
    sort_order: 10,
  },
  {
    title: "Brown Study",
    caption: "Cadmium yellow against a carved gilt frame.",
    image: "/images/art/labrador-portrait.jpeg",
    collection: "Interiors",
    tags: ["oil", "animal", "fireplace"],
    sort_order: 11,
  },
  {
    title: "Sentinel",
    caption: "Carved timber, bitumen and gold leaf at 130 × 180cm.",
    image: "/images/art/lion-relief.jpeg",
    collection: "Art",
    tags: ["sculptural", "statement", "timber"],
    sort_order: 12,
  },
  {
    title: "Northern Stallion",
    caption: "Mosaic blues against a cool grey ground.",
    image: "/images/art/stallion-mosaic.jpeg",
    collection: "Art",
    tags: ["mixed media", "animal", "square"],
    sort_order: 13,
  },
  {
    title: "Adorned",
    caption: "Float-mounted in dark walnut, in a quiet bedroom.",
    image: "/images/art/adorned-portrait.jpeg",
    collection: "Interiors",
    tags: ["portrait", "bedroom", "pattern"],
    sort_order: 14,
  },
];

export const messages = [
  {
    name: "Helen Marsden",
    email: "h.marsden@northgatelegal.co.uk",
    phone: "07700 900142",
    subject: "Viewing request — Heaton Grange",
    enquiry_type: "property",
    message:
      "We're relocating from Harrogate in November and Heaton Grange looks right for us. Could we arrange a viewing on a Saturday morning? We'd also like to know whether the vendor is in a chain.",
    source_page: "/properties/heaton-grange-detached-bolton",
    related_ref: "heaton-grange-detached-bolton",
    status: "new",
  },
  {
    name: "Tobi Adeyemi",
    email: "tobi@adeyemicapital.com",
    phone: "07700 900318",
    subject: "Tenancy schedule — Victoria Square block",
    enquiry_type: "investment",
    message:
      "I act for a private investor looking at mixed-use in the North West. Please could you send the full tenancy schedule and service charge budget for the Victoria Square block, along with the last two years of arrears history?",
    source_page: "/properties/victoria-square-investment-block-bolton",
    related_ref: "victoria-square-investment-block-bolton",
    status: "read",
  },
  {
    name: "Claire Whitfield",
    email: "claire.whitfield@gmail.com",
    phone: null,
    subject: "Commission enquiry — two spaniels",
    enquiry_type: "art",
    message:
      "I'd love a portrait of our two cocker spaniels in the style of Brown Study, ideally both in one painting. The wall above our fireplace is about 120cm wide. What would that cost and how long is the wait?",
    source_page: "/art/brown-study",
    related_ref: "brown-study",
    status: "new",
  },
  {
    name: "Martin Doyle",
    email: "mdoyle.lettings@outlook.com",
    phone: "07700 900577",
    subject: "Switching management — 9 properties",
    enquiry_type: "management",
    message:
      "I have nine properties across Farnworth and Little Lever currently with another agent and I'm not happy with the compliance side. What would a switch involve and what are your fees at that volume?",
    source_page: "/services",
    related_ref: null,
    status: "replied",
  },
  {
    name: "Rachel Oyelaran",
    email: "r.oyelaran@studiofield.co.uk",
    phone: "07700 900904",
    subject: "Art for a client's reception",
    enquiry_type: "art",
    message:
      "I'm an interior designer working on a professional services reception in Spinningfields, double-height with a lot of raking light. Sentinel looks like a strong fit. Is it still available and can you advise on fixing?",
    source_page: "/art/sentinel",
    related_ref: "sentinel",
    status: "new",
  },
];

export const subscribers = [
  { email: "investor.updates@wilkinsonpartners.co.uk", source: "footer" },
  { email: "j.kowalski@gmail.com", source: "blog" },
  { email: "studio@fieldandco.design", source: "art" },
];
